Update multipanel.py
ExaFEL/exafel_project pull request #28
Opened 2023-11-07 23:42 UTC by vganapati

Update multipanel.py to save the orientation in the H5 file.

2023-11-08 14:30 UTC, dermen approved these changes

2023-11-08 16:43 UTC, Baharis approved these changes
Other than preferences (I'd probably specify explicitly when `convert_numpy=True`, not `False`), I see no issues.

2023-11-08 16:59 UTC, nksauter requested changes
I'd like to ask for a few changes,
1) All instances of the word "rotation" in the file should be changed to "Umatrix".
2) The save_variable() function should be moved outside of the run_sim2h5 method.
3) It's alarming that the save_variable() function deletes data already written.  Is it not possible to create the dataset if it does not exist, but use "append" if it exists?

2023-11-09 22:21 UTC, vganapati commented
The deletion instead of appending is a hack, if a better way can be found in the future, this should be changed.

2023-11-09 22:21 UTC, merged